version: '3.7'

services:
  web:
    image: nginx:1.18
    container_name: web
    ports:
      - "8080:8080"
    volumes:
      - ./forDocker/nginx/default.conf:/etc/nginx/conf.d/default.conf 
      - ./public:/app/public
    depends_on:
      - app

  app:
    container_name: app
    build: .
    tty: true
    stdin_open: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    volumes:
      - ./forDocker/mysql/conf.d:/etc/mysql/conf.d
      - dbvol:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: "Asia/Tokyo"

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "9000:8080"
    depends_on:
      - db

  # データを放り込みたいときはSSL通信を無効にする
  #https-portal3000:
  #  image: steveltn/https-portal:1
  #  ports:
  #    - "80:8080"
  #    - "443:443"
  #  links:
  #    - web
  #  restart: always
  #  volumes:
  #    - ./certs:/var/lib/https-portal 
  #  environment:
  #    STAGE: local
  #    DOMAINS: 'test.enginingual.com -> http://web:80'
  #  depends_on:
  #    - web
  #  container_name: https-portal

volumes:
  dbvol: